/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUIcul;

/**
 *
 * @author thbar7035
 */
public class CulminatingGUI extends javax.swing.JFrame {
    int score = 0;
    int total = 0;
    int question = 0;
    
    
    
   

    /**
     * Creates new form CulminatingGUI
     */
    public CulminatingGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        aLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        cLabel = new javax.swing.JLabel();
        aTextLabel = new javax.swing.JLabel();
        bTextLabel = new javax.swing.JLabel();
        cTextLabel = new javax.swing.JLabel();
        inputField = new javax.swing.JTextField();
        markOutput = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        remarkLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        percentLabel = new javax.swing.JLabel();
        niceRemarkLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        titleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 51, 255));
        titleLabel.setText("QUESTIONERINGEST!");

        instructionsLabel.setBackground(new java.awt.Color(102, 0, 102));
        instructionsLabel.setFont(new java.awt.Font("NimbusSanNo5TCY", 0, 20)); // NOI18N
        instructionsLabel.setForeground(new java.awt.Color(51, 0, 51));
        instructionsLabel.setText("PUT IN 1 2 OR 3");

        aLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aLabel.setForeground(new java.awt.Color(255, 255, 255));
        aLabel.setText("1");

        bLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bLabel.setForeground(new java.awt.Color(255, 255, 255));
        bLabel.setText("2");

        cLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cLabel.setForeground(new java.awt.Color(255, 255, 255));
        cLabel.setText("3");

        aTextLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        aTextLabel.setText("Yes");

        bTextLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        bTextLabel.setText("No");

        cTextLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        cTextLabel.setText("Another No");

        markOutput.setForeground(new java.awt.Color(255, 255, 255));
        markOutput.setText("0/9");

        questionLabel.setBackground(new java.awt.Color(102, 0, 102));
        questionLabel.setFont(new java.awt.Font("NimbusSanNo5TCY", 0, 20)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(51, 0, 51));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("IS THE SKY BLUE?!?");

        remarkLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        remarkLabel.setForeground(new java.awt.Color(255, 255, 51));
        remarkLabel.setText("This Is Easy");

        jButton1.setText("Enter Answer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        percentLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        percentLabel.setForeground(new java.awt.Color(255, 255, 51));

        niceRemarkLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        niceRemarkLabel.setForeground(new java.awt.Color(102, 204, 255));
        niceRemarkLabel.setText("I believe in you");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(markOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bLabel)
                                    .addComponent(cLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cTextLabel)
                                    .addComponent(bTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remarkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(percentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(instructionsLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(niceRemarkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(niceRemarkLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remarkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(markOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        //declaring variables
        double answer;
        double percent;
        double rng;
        
        //random number for nice remarks
        rng = (int)Math.round(Math.random()*9+1);
        
        
        //take input
        answer = Double.parseDouble(inputField.getText());
       
        
        if (rng == 1){
            niceRemarkLabel.setText("You can do it");
        }
        if (rng == 2){
            niceRemarkLabel.setText("Anything you put your mind to!");
        }
        if (rng == 3){
            niceRemarkLabel.setText("You've got the right stuff!");
        }
        if (rng == 4){
            niceRemarkLabel.setText("Yeah! Do it!");
        }
        if (rng == 5){
            niceRemarkLabel.setText("You're smarter than you think!");
        }
        if (rng == 6){
            niceRemarkLabel.setText("Don't let a question stump you");
        }
        if (rng == 7){
            niceRemarkLabel.setText("I'm running out of ideas for inspiration");
        }
        if (rng == 8){
            niceRemarkLabel.setText("*Inspiration*");
        }
        if (rng == 9){
            niceRemarkLabel.setText("This variable is litterally called rng");
        }
        if (rng == 10){
            niceRemarkLabel.setText("I crammed this in last second for that sweet sweet rng");
        }
        
        
        
        
       
      //all questions
        //question 8 includes the game over sequence
        if (question==8){
    
         if (answer == 2){
                 score = score + 1;
                 remarkLabel.setText("It's weird that you know that");
             }
        else{
            remarkLabel.setText("SHREKED");
        }
         questionLabel.setText("GAME OVER");
            
         percent = (score/9)*100;
         percent = percent * 10;
         percent = Math.round(percent);
         percent = percent/10;
         
         remarkLabel.setText("You got " + score + " out of 9");
         percentLabel.setText("You got " + percent + "%");
        }
        
        if (question==7){
           
         if (answer == 3){
                 score = score + 1;
                 remarkLabel.setText("It's weird that you know that");
             }
        else{
            remarkLabel.setText("SHREKED");
        }
         questionLabel.setText("What colour is my cat");
        
             aTextLabel.setText("Black");
             bTextLabel.setText("Orange");
             cTextLabel.setText("White");
         total = total + 1;
         question = question + 1;
        }
        
        
        if (question==6){
       
         if (answer == 3){
                 score = score + 1;
                 remarkLabel.setText("THEY ONLY HAVE WHITE BOARDS!");
             }
        else{
            remarkLabel.setText("THEY ONLY HAVE WHITE BOARDS HAHA");
        }
         questionLabel.setText("What did Ben name his sumative project?");
        
             aTextLabel.setText("Summative");
             bTextLabel.setText("Summer tivs");
             cTextLabel.setText("Summa");
         total = total + 1;
         question = question + 1;
        }
        
        
        if (question==5){
         if (answer == 3){
                 score = score + 1;
                 remarkLabel.setText("ITS LEIF ERIKSON DAY");
             }
        else{
            remarkLabel.setText("ha,hahahaha");
        }
         questionLabel.setText("What colour are the chalk boards in the manufacturing room");
        
             aTextLabel.setText("Black");
             bTextLabel.setText("Green");
             cTextLabel.setText("White");
         total = total + 1;
         question = question + 1;
        }
        
        if (question==4){
         
         if (answer == 3){
                 score = score + 1;
                 remarkLabel.setText("OMGOMGOMGOMGOMG");
             }
        else{
            remarkLabel.setText("pft, ez pz rekt skrub");
        }
         questionLabel.setText("Who was the fella who found America");
        
             aTextLabel.setText("Napolean");
             bTextLabel.setText("Christpoher Columbus");
             cTextLabel.setText("Leif Erikson");
         total = total + 1;
         question = question + 1;
        }
        
        if (question==3){
         if (answer == 1){
                 score = score + 1;
                 remarkLabel.setText("Gooooooooood JOB");
             }
        else{
            remarkLabel.setText("*rasbery sound* u suc");
        }
         questionLabel.setText("Is black a colour?");
        
             aTextLabel.setText("Yes");
             bTextLabel.setText("No");
             cTextLabel.setText("Its a shade");
         total = total + 1;
         question = question + 1;
        }
        
        
        if (question==2){
           
         if (answer == 2){
                 score = score + 1;
                 remarkLabel.setText("LORDY LORDY, WE GOTTA SMARTY PANTS");
             }
        else{
            remarkLabel.setText("Ha!");
        }
         questionLabel.setText("Is red a colour?");
        
             aTextLabel.setText("Yes");
             bTextLabel.setText("No");
             cTextLabel.setText("Its a shade");
         total = total + 1;
         question = question + 1;
        }
        
        
        if (question==1){
        if (answer == 3){
            score = score + 1;
            remarkLabel.setText("Wow,you actually did it");
        }
        else{
            remarkLabel.setText("H-How did you mess that up?!?");
        }
        questionLabel.setText("What is the answer to life, the universe, and everything else?");
        
             aTextLabel.setText("Jesus");
             bTextLabel.setText("42");
             cTextLabel.setText("The Bee Movie");
        total = total + 1;
        question = question + 1;
        }
        
        if (question==0){
        if (answer == 1){
            score = score + 1;
            remarkLabel.setText("Yay");
        }
        else{
            remarkLabel.setText("OOF!");
        }
        questionLabel.setText("How many fingers does the average human have");
            
            aTextLabel.setText("20");
            bTextLabel.setText("5");
            cTextLabel.setText("10");
            total = total + 1;
            question = 1;
        }
        
        
        //resets the input box after you hit the button
        inputField.setText("");
        //displays your score in the bottum right
        markOutput.setText(score+"/9");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CulminatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CulminatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CulminatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CulminatingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CulminatingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JLabel aTextLabel;
    private javax.swing.JLabel bLabel;
    private javax.swing.JLabel bTextLabel;
    private javax.swing.JLabel cLabel;
    private javax.swing.JLabel cTextLabel;
    private javax.swing.JTextField inputField;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel markOutput;
    private javax.swing.JLabel niceRemarkLabel;
    private javax.swing.JLabel percentLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel remarkLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
